LIBRARIES=render.a(Bmp.o Font.o)
PROGRAMS=

all: $(LIBRARIES) $(PROGRAMS)

include ../Makefile.inc

# DO NOT DELETE THIS LINE - make depend depends on it

AdminConnection.o: ../Telnet/TelnetConnection.h ../Telnet/TelnetProxyServer.h
AdminConnection.o: ../Telnet/TelnetConfig.h ../NetCore/CConfig.h
AdminConnection.o: ../NetCore/Core.h ../NetCore/Adaptor.h
AdminConnection.o: ../NetCore/CSocket.h ../NetCore/comdomains.h
AdminConnection.o: ../Admin/TelnetProxyAdmin.h ../Http/HttpConnection.h
AdminConnection.o: ../Http/HttpMessage.h ../Emulation/TEmu.h
AdminConnection.o: AdminConnection.h Restore.h ../Emulation/TEmuVt102.h
AdminConnection.o: ../Emulation/TEScreen.h ../Emulation/TECommon.h
Bmp.o: Bmp.h ../Emulation/TECommon.h Font.h
Font.o: Font.h
Restore.o: Restore.h ../Emulation/TEmuVt102.h ../Emulation/TEmu.h
Restore.o: ../Emulation/TEScreen.h ../Emulation/TECommon.h
Restore.o: ../NetCore/Adaptor.h ../NetCore/Core.h ../NetCore/CConfig.h
Restore.o: ../NetCore/CSocket.h ../NetCore/comdomains.h
Restore.o: ../Emulation/Translation.h
AdminConnection.o: ../Telnet/TelnetProxyServer.h ../Telnet/TelnetConfig.h
AdminConnection.o: ../NetCore/CConfig.h ../NetCore/Core.h
AdminConnection.o: ../NetCore/Adaptor.h ../NetCore/CSocket.h
AdminConnection.o: ../NetCore/comdomains.h ../Admin/TelnetProxyAdmin.h
AdminConnection.o: ../Http/HttpConnection.h ../Http/HttpMessage.h
AdminConnection.o: ../Emulation/TEmu.h
Bmp.o: ../Emulation/TECommon.h
Restore.o: ../Emulation/TEmuVt102.h ../Emulation/TEmu.h
Restore.o: ../Emulation/TEScreen.h ../Emulation/TECommon.h
Restore.o: ../NetCore/Adaptor.h ../NetCore/Core.h ../NetCore/CConfig.h
Restore.o: ../NetCore/CSocket.h ../NetCore/comdomains.h
