LIBRARIES=render.a(Bmp.o Font.o)
PROGRAMS=

all: $(LIBRARIES) $(PROGRAMS)

include ../Makefile.inc

# DO NOT DELETE THIS LINE - make depend depends on it

./Bmp.o: Bmp.h ../Emulation/TECommon.h Font.h
./Font.o: Font.h
./Bmp.o: ../Emulation/TECommon.h
